Update README.md
mattermost/mattermost-plugin-zoom pull request #158
Opened 2020-09-01 20:57 UTC by justinegeffen

General typos and formatting.

2020-09-02 09:37 UTC, larkox approved these changes
LGTM. Thanks!

2020-09-04 18:24 UTC, hanzei approved these changes

2020-09-07 08:00 UTC, larkox requested changes
One small typo, and one addition.

2020-09-07 08:00 UTC, larkox commented on docs/installation/zoom-configuration/README.md
> +   * Users need to connect their Zoom account with their Mattermost account before they can use the integration. When they try to create a meeting for the first time, they'll receive a message to con
```suggestion
   * Users need to connect their Zoom account with their Mattermost account before they can use the integration. When they try to create a meeting for the first time, they'll receive a message to connect their account. They'll need to select **Approve** on a pop-up web page, in order to begin the meeting.
```

2020-09-07 08:00 UTC, larkox commented on docs/installation/zoom-configuration/README.md
> +   * Uses JWT to pass security tokens. This may not be sufficiently secure for some customers.
I would add something like:
* The users must have the same email registered both in Zoom and Mattermost.

2020-10-06 09:32 UTC, larkox approved these changes
LGTM

2020-10-06 09:33 UTC, merged