[GH-235] Refresh token on user level oauth (#235)
mattermost/mattermost-plugin-zoom pull request #242
Opened 2021-11-17 02:16 UTC by vicky-demansol

#### Summary

i think is only move the refresh token outside "if isAccountLevel" but if the refresh token function only for account level, how we get user level token ?
#### Ticket Link

https://github.com/mattermost/mattermost-plugin-zoom/issues/235

2021-11-17 02:16 UTC, mattermod commented
Hello @vicky-demansol,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-11-17 08:05 UTC, larkox commented
Thanks, @vicky-demansol but this won't work. If I understand the code correctly, you are just not making any distinction between AccountLevel and UserLevel by removing the if. Both tokens come from different places (take a look to the `getActiveClient` function), and have to be handled slightly different.

This may work if you instead of getting the token from the `getSuperUserToken` you get it directly from the client (since it is already fetch from the database), but then you also have to distinguish where you store it. You must store the account level one as the superuser token, or the user level one on the user information.

2021-11-25 13:13 UTC, larkox requested changes
I like the approach, but I fear it may not be handling all the cases correctly. Take a look at the comments.

2021-11-25 13:13 UTC, larkox commented on server/http.go
> +		err = p.setUserToken(userID, token)
This seems cleaner so far, but a few lines after (line 161) we are storing the token along the OAuthUserInfo. If we want to follow this pattern, we would need to refactor the token out of the OAuthUserInfo and fix whatever breaks from that.

Another solution would be to keep the current pattern, and just update the token when needed in the OAuthUserInfo structure when needed.

I leave up to you which path to take.

2021-11-25 13:13 UTC, larkox commented on server/plugin.go
> +	if err == nil {
We should handle the error, and remove this (I guess) debug lines.

2021-11-29 14:43 UTC, sibasankarnayak commented on server/plugin.go
> +	if err == nil {
if err != nil {
        p.API.LogInfo("error while fetching user token", "error",err.Error())
        retrun err
}

2021-11-29 14:46 UTC, sibasankarnayak commented on server/plugin.go
> +	}
```suggestion
	if err == nil {
		p.API.LogInfo(fmt.Sprintf("oldTokenIs===========================%s", *oldToken))
	}
```

2021-11-29 14:47 UTC, sibasankarnayak commented on server/plugin.go
> +	}
```suggestion
	}

```

2021-11-29 14:48 UTC, sibasankarnayak commented on server/plugin.go
> +	return token, nil
```suggestion

	return token, nil
```

2021-11-29 14:48 UTC, sibasankarnayak commented on server/plugin.go
> +		return errors.Wrap(err, "could not set token")
error should be logged here or in the function getting called

2021-11-29 14:49 UTC, sibasankarnayak commented on server/zoom/oauth.go
>  	if c.isAccountLevel {
remove unwanted change here

2021-12-11 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @BenLloydPearson @aspleenic

2021-12-20 14:22 UTC, sibasankarnayak approved these changes
Some non blocking changes are pending , code looks good so far.

2022-01-11 09:44 UTC, larkox approved these changes
LGTM, Thanks!

2022-01-25 16:08 UTC, dipak-demansol commented
@hanzei can you pls tell me what i have to Test in this PR? what is the expected result for this?

2022-01-26 09:08 UTC, dipak-demansol commented
> @larkox Can you please help with tests steps here? I'm not sure how to reproduce crated a token that timed out.

@larkox @hanzei is this related to this? https://github.com/mattermost/mattermost-plugin-zoom/issues/239

2022-01-26 09:32 UTC, hanzei commented
@dipak-demansol Yes

2022-01-26 13:53 UTC, larkox commented
I don't remember the timeline 100%, but in the old version, after you connect, if you wait for, I think, one hour, the token will be outdated and will force you to disconnect and connect again.

In order to test it, have two environments: one with the new version, and one with the old, and connect to zoom (on user level oauth) roughly at the same time. Then let that simmer for a few hours (or overnight), and try to create a new meeting. The old version should fail, saying that the token is expired, or something like that, and the new version should work without issues.

It would be useful also to have a third environment with account level app, to see if that is still working fine.

2022-02-01 08:37 UTC, dipak-demansol approved these changes
**LGTM**, Tested With Two server, 1st server had a market zoom plugin on a Chrome browser and 2nd server had a PR_code zoom app on the Brave browser, after 6 hour issue generated in the 1st server but the same issue not generated in the 2nd server.  
**Additional Info** :-  with the chrome browser and 2nd server when i create zoom meeting and join the meeting then i'm successfully join the meeting but in the brew browser with the 2nd server when i perform the same step then zoom don't identify me as a host and its wait for start the meeting. i will discuss with dylan about that.

2022-02-07 10:44 UTC, merged