[GH-283]: Fixed issue #283 'Removed the code for depreciated JWT
mattermost/mattermost-plugin-zoom pull request #299
Opened 2023-06-16 13:47 UTC by Kshitij-Katiyar

**Summary** 
- Zoom has depreciated its JWT authentication offering so we have also formally deprecated the JWT offering and removed it from the code.

- [Issue #283](https://github.com/mattermost/mattermost-plugin-zoom/issues/283)

2023-06-16 13:48 UTC, mattermost-build commented
Hello @Kshitij-Katiyar,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-07-04 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-07-05 20:22 UTC, mickmister requested changes
Just one request, otherwise LGTM :+1:

2023-07-05 20:22 UTC, mickmister commented on server/configuration.go
> +	if isCloud { // OAuth for either platform
We want to just remove this if condition, and have the block run unconditionally

```suggestion
```

2023-07-06 13:57 UTC, mickmister commented on server/configuration.go
> +	if isCloud { // OAuth for either platform
As a follow up explanation here, every other condition removed in this PR is `OAuthEnabled() &&`, whereas this one is `OAuthEnabled() ||` so we treat it slightly differently.

2023-07-06 13:58 UTC, mickmister approved these changes

2023-10-10 07:25 UTC, hanzei requested changes
LGTM, one blocking documentation comment

2023-10-10 07:25 UTC, hanzei commented on docs/installation/mattermost-setup.md
>  * If you are using Webhooks or Deauthorization, make sure you hit the **Regenerate** button on **Webhook Secret** field.
Given that OAuth is now the only way to connect, do we even need the `How are your users connecting to Zoom?` paragraph?

2023-10-10 07:25 UTC, hanzei commented on server/zoom/oauth.go
> -
Nit: unrelated change

2023-10-10 07:30 UTC, hanzei commented
@mgdelacroix I'm going to remove you from the reviewers list as you seem too busy to review it currently.

2023-10-10 10:25 UTC, hanzei approved these changes

2023-10-10 10:25 UTC, hanzei commented
@DHaussermann Ready for your review

2023-10-24 04:46 UTC, mickmister commented
Note that we've merged a PR https://github.com/mattermost/mattermost-plugin-zoom/pull/310 that removes JWT from the readme, which had some merge conflicts here

2023-10-24 13:05 UTC, avas27JTG commented
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/283

2023-10-25 09:05 UTC, AayushChaudhary0001 commented
Tested and Approved

This PR is tested for the following scenarios:-

- Change in the plugin config settings
- Updated readme.md file

All changes seems fine and are working perfect, LGTM

2023-10-25 09:56 UTC, AayushChaudhary0001 approved these changes

2023-10-27 13:26 UTC, merged